version: '3'

services:
  db:
    image: mysql:8.0.29
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: "recipedb"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    ports:
      - "13306:3306"
#      - '3306:3306' #localhostにいるdockerでもなんでもないmysqlのポートと被ってる → コンテナのIPアドレスのポート指定するから関係なかった。。
    # expose:
    #   - '3306'
    # expose:
    #   - '22'
    volumes:
      - ./Docker/initdb:/docker-entrypoint-initdb.d
      # データを永続的に保持するためにdbディレクトリを配置
      - ./Docker/initdb/db:/var/lib/mysql
volumes:
  mysql_data: