version:  2.1
jobs:
    test:
        docker:
          - image: cimg/openjdk:11.0.12 #テスト用イメージ

        working_directory: ~/select-recipes

        environment:
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx3200m
          TERM: dumb

        steps:
           - checkout

           - restore_cache:
               keys:
               - v1-dependencies-{{ checksum "build.gradle" }}
               - v1-dependencies-

           - run: gradle dependencies

           - save_cache:
               paths:
                  - ~/.gradle
               key: v1-dependencies-{{ checksum "build.gradle" }}

           - run: gradle test

workflows:
    version: 2
    # test_and_deploy ジョブ:テストは常時行い、デプロイはmainに向けられたときのみ行う
    test:
        # testジョブとdeployジョブを登録する
        jobs:
            - test
            - deploy:
                requires:
                  - test
                # filters: 
                #     branches:
                #         only: master #デプロイするのはmainブランチにプッシュされたときのみ